name: flutter_secured_storage_example
description: Demonstrates how to use the flutter_secured_storage plugin.

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_secured_storage:
    path: ../
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true